wandb:
  run_name: "weblab-GENIAC/Tanuki-8x8B-dpo-v1.0" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 2
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  max_model_len: 3500 # update 
  pretrained_model_name_or_path: "weblab-GENIAC/Tanuki-8x8B-dpo-v1.0" #if you use openai api, put the name of model
  chat_template: "weblab-GENIAC/Tanuki-8x8B-dpo-v1.0"
  size_category: "30B≤"
  size: 46702792704
  release_date: "8/30/2024"